patched for kernel 5.x.x with help of > https://aur.archlinux.org/packages/npreal2/

diff --git a/mxinst_auto b/mxinst_auto
--- a/mxinst_auto
+++ b/mxinst_auto
@@ -1,5 +1,5 @@
 ##########################################################################
-#   Copyright (C) 2003-2017  Moxa Inc.
+#   Copyright (C) 2003-2015  Moxa Inc.
 #   All Rights Reserved.
 #
 #
@@ -12,13 +12,39 @@
 ################################################################################
 # define value and default value setting
 ################################################################################
+
+
+# Parse params
+
+while [ $# -ge 1 ]
+do
+key="$1"
+case $key in
+    --use-ssl)
+        PARAM_SSL="y"
+    ;;
+    --no-ssl)
+        PARAM_SSL=n
+    ;;
+    --replace)
+        PARAM_REPLACE="y"
+    ;;
+    --no-replace)
+        PARAM_REPLACE="n"
+    ;;
+    *)
+    ;;
+esac
+shift
+done
+
 DirTmp=$0
 DirTmp=${DirTmp%/mxinst}
 TempDir=$DirTmp
 
 NPPATH="/usr/lib/npreal2"
 ProductName="MOXA NPort Server Real TTY Driver"
-ProductVer=`awk '{if($2=="NPREAL_VERSION"){print $3}}' np_ver.h`
+ProductVer=""
 OS="linux"
 Device=""
 check=""
@@ -27,21 +53,6 @@ EntryPwd=`pwd`
 driverPath="/usr/lib/npreal2/driver"
 MX_MOD=npreal2
 
-#Parameters
-MX_VERSION=3
-MX_PATCH_LEVEL=0
-MX_SUBLEVEL=0
-MX_VERSION_CODE=$(( ($MX_VERSION<<16)+($MX_PATCH_LEVEL<<8)+$MX_SUBLEVEL ))
-
-K_MODULE_VERSION=$(uname -r)
-K_RELEASE=$(echo $K_MODULE_VERSION | sed -e "s/-.*//g")
-K_VERSION=$(echo $K_RELEASE | cut -d '.' -f 1)
-K_PATCH_LEVEL=$(echo $K_RELEASE | cut -d '.' -f 2)
-K_SUBLEVEL=$(echo $K_RELEASE | cut -d '.' -f 3)
-K_VERSION_CODE=$(( ($K_VERSION<<16)+($K_PATCH_LEVEL<<8)+$K_SUBLEVEL ))
-
-K_SOURCE=/lib/modules/$K_MODULE_VERSION/build
-LINUX_DIS=$(grep '[0-9]' /etc/issue )
 
 ################################################################################
 # interrupt_quit1()
@@ -106,34 +117,70 @@ get_OsName() {
     fi
 }
 
-################################################################################
-# check_env()
-#   Check the environment for installation
-################################################################################
-check_env() {
-#Check kernel source
-if test  ! -e $K_SOURCE
-then
-echo "*********************************ERROR********************************"
-echo " Unable to locate matching source for kernel $K_MODULE_VERSION."
-echo " Please install proper kernel-header/source or contact support@moxa.com."
-echo "**********************************************************************"
-exit 1
-fi
 
-#Check supported kernel version
-if test $MX_VERSION_CODE -gt $K_VERSION_CODE
-then
-echo "********************************WARNING**********************************"
-echo " $ProductName may not be compatible with"
-echo " Linux Kernel versions $K_MODULE_VERSION ."
-echo " To download the available driver, please visit Moxa at: http://www.moxa.com"
-echo " If you have questions, please contact Moxa support at: support@moxa.com"
-echo "*************************************************************************"
-exit 1
-fi
+################################################################################
+# tar_files()
+#   tar the needed file to disk at $TempDir
+#   And copy the Driver.o file
+################################################################################
+tar_files() {
+
+    echo -n "Tar files, please wait ..."
+    [ -d $TempDir ] || mkdir $TempDir > /dev/null 2>&1
+    cd $TempDir
+    #[ "$Device" = "harddisk" ] || {
+    #    tar xvf $Device $TempDir/linux.tar.Z > /dev/null 2>&1
+    #    [ $? != 0 ] && {
+    #        [ -d $TempDir ] && rm -rf $TempDir > /dev/null 2>&1
+    #        echo "\nDevice name error ! It cannot tar file !"
+    #        exit 1
+    #    }
+    #}
+
+    #gunzip $TempDir/linux.tar.Z > /dev/null 2>&1
+    #tar xvf $TempDir/linux.tar > /dev/null 2>&1
+    tar xvfz $TempDir/linux.tgz > /dev/null 2>&1
+
+    #rm -rf linux.tar
+    echo " OK!"
 }
 
+################################################################################
+# chk_libssl()
+#   Check /usr/lib/libssl.so.x
+#   and link to /tmp/moxa/libsll.so
+################################################################################
+chk_libssl() {
+	sslpath=$(find /usr/lib64 -name "libssl.so*" 2> /dev/null)
+
+    if [ -z "$sslpath" ]
+	then
+		sslpath=$(find /usr/lib -name "libssl.so*" 2> /dev/null)
+		newsslpath=$(find /usr/lib/i386-linux-gnu -name "libssl.so*" 2> /dev/null)
+        if [ -z "$sslpath" ]
+        then
+        	echo
+        	echo 'Can not find libssl.so file in your system,'
+        	echo 'Please install openssl package if you want to use'
+        	echo 'security function.'
+        	exit 0
+       	else
+		if [ -z "$newsslpath" ]
+		then
+			echo "libssl.so.x.x in /usr/lib/"
+       			ls /usr/lib | grep libssl.so* | head -1 |
+	       		awk '{system("ln -s /usr/lib/"$0 " libssl.so")}'
+		else
+			echo "libssl.so.x.x in /usr/lib/i386-linux-gnu"
+       			ls /usr/lib/i386-linux-gnu | grep libssl.so* | head -1 |
+	       		awk '{system("ln -s /usr/lib/i386-linux-gnu/"$0 " libssl.so")}'
+		fi
+       	fi
+    else
+       	ls /usr/lib64 | grep libssl.so* | head -1 |
+       	awk '{system("ln -s /usr/lib64/"$0 " libssl.so")}'
+    fi
+}
 
 ########################################################
 #
@@ -150,9 +197,11 @@ then
     exit 1
 fi
 
+ProductVer=`awk '{if($2=="NPREAL_VERSION"){print $3}}' np_ver.h`
+
 echo -n "
 ===============================================================================
-Copyright (C) 2002-2017  Moxa Inc.
+Copyright (C) 2002-2015  Moxa Inc.
 All Rights Reserved.
 
 $ProductName "
@@ -164,45 +213,44 @@ System Information: Kernel `uname -r`; Machine `uname -m`.
 ===============================================================================
 "
 
-check_env 
+
 
 get_OsName
 
-if [ "$OS" = "debian" ] 
+if [ "$OS" = "debian" ]
 then
     touch /etc/init.d/npreals
 fi
-
 trap interrupt_quit2 1 3 9 15       # trap signal
 trap interrupt_nothing2 2           # trap signal SIGINT
-
 
 ########################################################
 # check configuration file. (npreal2d.cf)
 ########################################################
-if [ -f /usr/lib/npreal2/driver/npreal2d.cf ]
-then
-    echo 'There is an Real TTY Driver installed in your system.'
-    echo 'Continue to install will overwrite the old driver.'
-    echo 'Do you want to continue installing? [y/N].'
-
-    read check
-    case $check in
-    [n])
-        exit 0
-        ;;
-    [N])
-        exit 0
-        ;;
-    [y])
-        ;;
-    [Y])
-        ;;
-    *)
-        exit 0
-        ;;
-    esac
-fi
+#if [ -f /usr/lib/npreal2/driver/npreal2d.cf ]
+#then
+#    echo 'There is an Real TTY Driver installed in your system.'
+#    echo 'Continue to install will overwrite the old driver.'
+#    echo 'Do you want to continue installing? [y/N].'
+#
+#    if [ -z "$PARAM_REPLACE" ]; then read check; else check=$PARAM_REPLACE; fi
+#
+#    case $check in
+#    [n])
+#        exit 0
+#        ;;
+#    [N])
+#        exit 0
+#        ;;
+#    [y])
+#        ;;
+#    [Y])
+#        ;;
+#    *)
+#        exit 0
+#        ;;
+#    esac
+#fi
 
 ########################################################
 # rmmove module
@@ -217,8 +265,10 @@ awk '$0 != "" {system("rmmod npreal2")}'
 # install driver
 ########################################################
 echo ''
+tar_files
 
 echo "Building driver..."
+
 
 mkdir -p /lib/modules/`uname -r`/kernel/drivers/char > /dev/null 2>&1
 mkdir -p /lib/modules/`uname -r`/misc > /dev/null 2>&1
@@ -229,7 +279,7 @@ echo 'you might choose [y] to enable the SSL function.'
 echo 'Note: This function support RealCOM with secure mode only.'
 echo 'Do you want to enable secure function? [y/N].'
 
-read check
+if [ -z "$PARAM_SSL" ]; then read check; else check=$PARAM_SSL; fi
 case $check in
 [n])
     if [ "$1" = "SP1" ]
@@ -241,7 +291,7 @@ case $check in
 		make all PATH1=$(pwd) POLLING=-DOFFLINE_POLLING
     else
         make all PATH1=$(pwd)
-    fi 
+    fi
     ;;
 [N])
     if [ "$1" = "SP1" ]
@@ -253,9 +303,14 @@ case $check in
 		make all PATH1=$(pwd) POLLING=-DOFFLINE_POLLING
     else
         make all PATH1=$(pwd)
-    fi 
+    fi
     ;;
 [y])
+	if [ ! -f "$TempDir/libssl.so" ]
+	then
+		chk_libssl
+	fi
+
 	if [ "$1" = "SP1" ]
 	then
 		make SP1_ssl PATH1=$(pwd)
@@ -274,9 +329,14 @@ case $check in
 		make ssl PATH1=$(pwd) POLLING=-DOFFLINE_POLLING
 	else
 		make ssl PATH1=$(pwd)
-	fi 
+	fi
     ;;
 [Y])
+	if [ ! -f "TempDir/libssl.so" ]
+	then
+		chk_libssl
+	fi
+
 	if [ "$1" = "SP1" ]
 	then
 		make SP1_ssl PATH1=$(pwd)
@@ -295,7 +355,7 @@ case $check in
 		make ssl PATH1=$(pwd) POLLING=-DOFFLINE_POLLING
 	else
 		make ssl PATH1=$(pwd)
-	fi 
+	fi
     ;;
 *)
 	if [ "$1" = "polling" ]
@@ -364,8 +424,9 @@ cp -f $NowPath/mxmknod     $driverPath
 cp -f $NowPath/mxrmnod     $driverPath
 cp -f $NowPath/mxuninst    $driverPath
 cp -f $NowPath/mxsetsec    $driverPath
-cp -f $NowPath/README.TXT  $NPPATH
-cp -f $NowPath/VERSION.TXT $NPPATH
+cp -f $NowPath/../README.TXT  $NPPATH
+cp -f $NowPath/../VERSION.TXT $NPPATH
+cp -f $NowPath/kernel3.txt $NPPATH
 echo "OK!"
 
 
@@ -375,10 +436,8 @@ echo "OK!"
 #cp -f $driverPath/npreal2.o /lib/modules/`uname -r`/misc
 
 
-ps -ef | grep npreal2 |
-awk '$0 !~ /grep/ {system("kill -15 "$2)}'
-ps -ef | grep npreal2 |
-awk '$0 !~ /grep/ {system("kill -9 "$2)}'
+ps -ef | grep npreal2 | awk '$0 !~ /grep|mxinst/ {system("kill -15 "$2)}'
+ps -ef | grep npreal2 | awk '$0 !~ /grep|mxinst/ {system("kill -9 "$2)}'
 
 
 
@@ -388,7 +447,7 @@ awk '$0 !~ /grep/ {system("kill -9 "$2)}'
 # load module
 ########################################################
 echo "Load driver..."
-modprobe $MX_MOD 
+modprobe $MX_MOD
 [ "$?" = "0" ] || {
     echo ""
     echo "Failed!!!  please contact the provider"
